### ISSUE TITLE
Stop writing spaghetti code

### ISSUE THREAD

**Issue by Clemens-E** [GabijusEK/Bag#43]
Stop writing spaghetti code.
Create short and maintainable modules instead of bashing it all into *one* **big** file

**Comment by WhoozardHat** [comment]
+1

bad devs tbh

**Comment by GabijusEK** [comment]
Yep! Completely aware of it!

**Comment by Clemens-E** [comment]
> +1
> 
> bad devs tbh

Well nobody starts perfect, everyone has to start somewhere, Its just important to keep improving.
(I'm not a good dev either)

**Comment by GabijusEK** [comment]
Quick update on this!
We've split everything up into separate modules, so everything is a lot cleaner now!
